"""Allow NULL user_id for public lists

Revision ID: 98512b70ce94
Revises: 15ce9c9e3881
Create Date: 2025-12-04 20:46:25.553115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98512b70ce94'
down_revision = '15ce9c9e3881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swedish', sa.String(length=255), nullable=False),
    sa.Column('english', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_word')
    # ### end Alembic commands ###
